import type { Metadata } from "next";
import "../styles/globals.css";
import { Card } from "@/components/ui/card";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/custom/Navbar";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <ThemeProvider>
          <body className={`${inter.className} min-h-screen flex flex-col`}>
            <Navbar />
            {/* <div className='flex-1 bg-red-200'>{children}</div> */}
            <Card className="flex-1 border-none rounded-none flex">
              {children}
            </Card>
          </body>
        </ThemeProvider>
      </ClerkProvider>
    </html>
  );
}
